### ISSUE TITLE
Managed Accounts

### ISSUE THREAD

**Issue by dphildebrandt** [RemiRigal/Plex-Auto-Languages#3]
Doesn't seem to work with managed accounts ie, Plex Home users.

**Comment by BEisem** [comment]
Yes, I noticed this as well. I think it works for shared users, interestingly, but not managed home users.

**Comment by dphildebrandt** [comment]
Yup, can confirm shared users work great.

**Comment by BEisem** [comment]
I have a hunch the reason it's not working for managed users is because managed users have their own Plex token, separate from the main user. The token is a bit more difficult to find, but you can figure it out by viewing an item from the managed user's web interface, and searching the page source for "token."

I'm currently trying to figure out a way to run a separate Plex-Auto-Languages docker container and feeding it the managed user's token in the yaml file. This is clearly not an ideal situation, but might work until/if a fix is provided by the developer.

**Comment by RemiRigal** [comment]
Currently only shared users are supported, I'm working on adding support for managed users as well but for some reason it cannot be done in the same way.

**Comment by dphildebrandt** [comment]
Yeah the managed users are set up a bit differently/more complicated than regular shared users.

**Comment by RemiRigal** [comment]
Thank you for the fast response. It should be fixed in v1.0.10.

**Comment by BEisem** [comment]
Also, I just tested with a managed user, and I don't believe it's working there either. Not sure if the fix will also fix that? But I'll test as soon as it is deployed.

**Comment by BEisem** [comment]
That fixed it, thanks!

**Comment by dphildebrandt** [comment]
Works flawlessly, thanks!
